version: "3.8"

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - db
    volumes:
      - .:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  db:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  elasticsearch: # Assuming you also run Elasticsearch via Docker Compose
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1 # Use a matching version
    container_name: es01
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # For easier local dev, secure for production
    ports:
      - "9200:9200"
    volumes:
      - esdata01:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.1 # Use a matching version
    container_name: kibana01
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: '["http://es01:9200"]' # Points to your Elasticsearch container
    depends_on:
      - elasticsearch

volumes:
  postgres-data:
