apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-storage-pvc
spec:
  storageClassName: manual # Must match the PV's storageClassName
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # Request storage, should be less than or equal to PV capacity