apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-storage-pv
  labels:
    type: local
spec:
  storageClassName: manual # Or your specific storage class if you have one
  capacity:
    storage: 5Gi # Adjust size as needed for your model
  accessModes:
    - ReadWriteOnce # Can be mounted by a single node (suitable for Minikube)
  hostPath:
    path: "/mnt/data/model-storage" # Path on the Minikube node (or host)