# k8s-postgres.yaml
apiVersion: v1
kind: Service
metadata:
  name: postgres-service # DNS name used by other services (matches POSTGRES_HOST)
spec:
  ports:
    - port: 5432 # Port the service exposes (matches POSTGRES_PORT)
      targetPort: 5432 # Port the container listens on
  selector:
    app: postgres
  clusterIP: None # Headless service for StatefulSet

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "postgres-service"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine # Or your preferred version
          ports:
            - containerPort: 5432
              name: postgresdb
          env:
            # Explicitly map required PG env vars from the secret
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_DB
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: postgres # Store data in a sub-directory within the volume
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi # Adjusted size, modify as needed
        # storageClassName: "your-storage-class" # Optional: specify if needed
