# load-generator-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
spec:
  replicas: 3 # Start with 3 load generator pods, increase if needed
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      containers:
      - name: curl-loader
        image: curlimages/curl
        # Command to run multiple loops inside each pod
        command: ["sh", "-c"]
        args:
          - |
            apk add --no-cache procps;
            echo 'Starting parallel load generation in pod...';
            run_load() {
              while true; do
                curl -s -o /dev/null -X POST -H 'Content-Type: application/json' -d "{\"question\":\"multi-pod load test $(date +%s) $1\"}" http://fastapi-service/api/v1/qna/ask;
                sleep 0.01;
              done
            }
            NUM_PARALLEL=100 # Number of loops per pod
            echo "Launching $NUM_PARALLEL parallel curl loops in this pod..."
            for i in $(seq 1 $NUM_PARALLEL); do run_load $i & done
            echo "Load generators running. Waiting indefinitely...";
            wait
