filebeatConfig:
  filebeat.yml: |
    filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log

    processors:
      - add_kubernetes_metadata:
          in_cluster: true

    output.elasticsearch:
      hosts: ['https://elasticsearch-master.elastic-system.svc.cluster.local:9200']
      username: "elastic"
      password: "dAW3sQtdXeX4AduS"
      ssl.verification_mode: none

    setup.kibana:
      host: "http://elasticsearch-master.elastic-system.svc.cluster.local:5601"

daemonset:
  enabled: true
