---
- hosts: localhost
  connection: local
  tasks:
    - name: Apply nginx ConfigMap
      k8s:
        state: present
        src: ../k8s/nginx-configmap.yaml
        namespace: default   # ✅ Required

    - name: Apply fastapi deployment
      k8s:
        state: present
        src: ../k8s/fastapi-deployment.yaml
        namespace: default

    - name: Apply fastapi service
      k8s:
        state: present
        src: ../k8s/fastapi-service.yaml
        namespace: default


    - name: Apply nginx deployment and service
      k8s:
        state: present
        src: ../k8s/nginx-deployment.yaml
        namespace: default   # ✅ Required
